### PR TITLE
Call the close function when the end signal is emitted

### PR DESCRIPTION
**Pull request by stylesuxx**
It seems the close method is never called, thus the browser is never closed.

When you run the tests in `proxy-lists` this is not an issue, because it is run as a separate process which is killed once the tests are finished, thus also closing the browser.

I am not sure if I am missing something.

**Edit**:
Since the tests are failing, I am obviously missing something...

Should the implementing library call the sourcers close function? In this case I think it should be documented...

### CODE REVIEW

**Comment by chill117** [comment]
A new browser tab is created whenever a source calls the `options.newPage` function. These tabs should be closed after the source sends its end event. This can be done by the `dataSourcer.getDataFromSource` method:
* Hold an array of all pages that were created by a source during the execution of the source's `getData` method
* After the end event from the source's `getData` method, close all those pages.
* Should not close the browser or any of the pages used by other sources

**Comment by stylesuxx** [comment]
Is this implemented functionality or planned functionality? Because as of now, the tabs are not closing for me.

**Comment by chill117** [comment]
This is not how it currently works - but it should be done this way. The tabs should be cleaned up properly once they are no longer needed. Right now they are only closed when you call `dataSourcer.close()` - which is not desirable as you pointed out.

**Comment by chill117** [comment]
And sorry for the confusing title rename - I thought this was an issue not a PR.

**Comment by stylesuxx** [comment]
I see - yes, I totally agree with this.
No problem, I just needed a quick fix - this did it for me and I thought I'd submit a PR - just in case ;-)

**Comment by chill117** [comment]
Issue #17 has been done and included in the latest release - so the browser tabs should be cleaned-up properly now.

**Comment by stylesuxx** [comment]
This is working partially for me: The tabs are closed once the sourcer is done, still the browser is not closed. Tried with `proxy-lists` and `data-sourcer` latest master branch.

**Pull request closed without merging**
